### ISSUE TITLE
May need add if_link.h in include/uapi/linux/ ?

### ISSUE THREAD

**Issue by aguaiyoung** [libbpf/bpftool#6]
make error build in clang 11.0.0 like that:
netlink_dumper.c:50:14: error: use of undeclared identifier 'XDP_ATTACHED_MULTI'
        if (mode == XDP_ATTACHED_MULTI) {
                    ^
netlink_dumper.c:55:24: error: use of undeclared identifier 'IFLA_XDP_SKB_PROG_ID'; did you mean 'IFLA_XDP_PROG_ID'?
                xdp_dump_prog_id(tb, IFLA_XDP_SKB_PROG_ID, "generic", true);
                                     ^~~~~~~~~~~~~~~~~~~~
                                     IFLA_XDP_PROG_ID
maybe miss if_link.h in usersapce?
like add libbpf that https://github.com/libbpf/libbpf/tree/master/include/uapi/linux

**Comment by qmonnet** [comment]
On my setup, those two flags `XDP_ATTACHED_MULTI` and `IFLA_XDP_PROG_ID` are defined in `/usr/include/linux/if_link.h`, which is pulled from `/usr/include/linux/rtnetlink.h`, included in `netlink_dumper.c` as `#include <linux/rtnetlink.h>`. Both headers seem to be shipped on Ubuntu by default, as part of `linux-libc-dev`.

Are you missing those headers on your system, or are they too old to contain the relevant flags? I'm just trying to understand where the difference comes from. To cover the second case we'll likely have to ship `if_link.h` indeed.

**Comment by aguaiyoung** [comment]
/usr/include/linux/if_link.h is generate by kenrel-headers, but some user symstem is old kernel like me.
so we may try to compatible it in setup stage,just bpftool is userspace tool.
thank you for explain and fix it .
