### ISSUE TITLE
missing zstd library for libelf when building statically on Ubuntu 24.04

### ISSUE THREAD

**Issue by mtardy** [libbpf/bpftool#152]
When building bpftool statically on Ubuntu 24.04 (note that it works fine on 22.04), `-lzstd` must be added to `LIBS` and `BOOTSTRAP_LIBS`. See my "live patch" https://github.com/cilium/tetragon/pull/2777/commits/8e994cf0bc2ad2ccd88ba9a490913052a1b9a825.

Would it make sense to upstream that? I would be happy to.

I have a repro, do the following steps with `ubuntu:22.04` and `ubuntu:24.04` (replace clang 15 with clang 18 on 24.04)
```
apt-get update && apt-get install -y --no-install-recommends clang-15 libclang-common-15-dev libclang-cpp15 libllvm15 llvm-15-linker-tools libclang1-15 llvm-15 llvm-15-runtime llvm-15-linker-tools make
apt-get update && apt-get install -y curl git llvm gcc pkg-config zlib1g-dev libelf-dev libcap-dev
git clone https://github.com/libbpf/bpftool.git
cd bpftool
git submodule update --init --recursive
make -C src EXTRA_CFLAGS=--static EXTRA_LDFLAGS=-v -j $(nproc) && strip src/bpftool
```

**Comment by qmonnet** [comment]
Thanks for the report! We'll need to update both the kernel and the mirror repo, independently. Do you have more context on the change, by any chance? Is there a way to figure out whether the `-lzstd` is required without having to add a new set of probes?

**Comment by petrutlucian94** [comment]
I hit the same problem, for what is worth zstd is required by libelf:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libelf.a(elf_compress.o): in function `__libelf_decompress_elf':
(.text+0xd45): undefined reference to `ZSTD_decompress'
```

**Comment by qmonnet** [comment]
Yes. Elfutils commit [a5b07cdf9c49](https://sourceware.org/git/?p=elfutils.git;a=commit;h=a5b07cdf9c491fb7a4a16598c482c68b718f59b9) adds support for ZSTD compression, since elfutils 0.189.

Ubuntu 22.04 [ships version 0.186 (or 0.188 in backports)](https://launchpad.net/ubuntu/jammy/+package/libelf-dev), Ubuntu 24.04 [has 0.189 or 0.190](https://launchpad.net/ubuntu/noble/+package/libelf-dev) depending on the arch.

**Comment by qmonnet** [comment]
@mtardy Were you working on upstreaming a fix at all for this issue? I can't remember

**Comment by mtardy** [comment]
> @mtardy Were you working on upstreaming a fix at all for this issue? I can't remember

I'm not sorry!

**Comment by qmonnet** [comment]
https://lore.kernel.org/bpf/20241211093114.263742-1-leo.yan@arm.com/t/#u

**Comment by qmonnet** [comment]
Merged in perf tree and made it to linux-next, but this hasn't been synced with bpf-next (from where we update this mirror repo) yet.

**Comment by qmonnet** [comment]
Fixed in Makefile with https://github.com/libbpf/bpftool/commit/67f1758bd7889bbec1ec5dab56888b19ec7212f3, corresponding probe in GitHub mirror repo in https://github.com/libbpf/bpftool/commit/f964613f2218981e81c6cf331b79f531bbaa148a.

We still need the flag and probe for libbfd, though (#73).
